export const products = [
  {
    id: "p1",
    slug: "niacinamide-clarity-serum",
    name: "Niacinamide Clarity Serum",
    ingredient: "Niacinamide 10% + Zinc PCA",
    price: 649,
    originalPrice: null,
    badge: "Bestseller",
    badgeType: "accent",
    image: "/images/Anti-Aging Serum.jpg",
    tags: ["Oil Control", "Brightening"],
    concerns: ["pigmentation", "oily"],
    skinTypes: ["oily", "combination", "normal"],
    rating: "4.9 (2.1k)",
    desc: "A potent serum that targets blemishes, minimizes enlarged pores, and regulates sebum production for a clear, balanced complexion.",
    howToUse: "Apply 2-3 drops to entire face morning and evening before heavier creams.",
  },
  {
    id: "p2",
    slug: "salicylic-acid-cleanser",
    name: "Salicylic Acid Cleanser",
    ingredient: "Salicylic Acid 2% + Aloe Vera",
    price: 449,
    originalPrice: null,
    badge: "New",
    badgeType: "primary",
    image: "/images/Facewash.jpg",
    tags: ["Acne Control"],
    concerns: ["acne", "oily"],
    skinTypes: ["oily", "combination", "normal"],
    rating: "4.7 (1.4k)",
    desc: "A lightly foaming daily cleanser that deeply penetrates pores to clear severe acne blemishes and prevent new breakouts without stripping skin.",
    howToUse: "Massage onto wet skin in a gentle, circular motion. Rinse well.",
  },
  {
    id: "p3",
    slug: "invisible-uv-shield-spf-50",
    name: "Invisible UV Shield SPF 50",
    ingredient: "Zinc Oxide + Vitamin E",
    price: 599,
    originalPrice: null,
    badge: null,
    badgeType: null,
    image: "/images/Sunscreen.jpg",
    tags: ["Sun Protection"],
    concerns: ["sun-protection", "anti-aging"],
    skinTypes: ["all"],
    rating: "4.8 (980)",
    desc: "A lightweight, non-comedogenic physical sunscreen that leaves zero white-cast. Broad-spectrum protection tailored for South Asian climates.",
    howToUse: "Apply generously as the final step of your morning skincare routine, 15 minutes before sun exposure.",
  },
  {
    id: "p4",
    slug: "hydra-barrier-moisturizer",
    name: "Hydra-Barrier Moisturizer",
    ingredient: "Hyaluronic Acid + Ceramides",
    price: 549,
    originalPrice: 699,
    badge: "Bestseller",
    badgeType: "accent",
    image: "/images/Moisturizer.jpg",
    tags: ["Hydration", "Sensitive"],
    concerns: ["dryness", "sensitive"],
    skinTypes: ["dry", "normal", "sensitive"],
    rating: "4.9 (1.8k)",
    desc: "A rich but non-greasy cream that instantly replenishes the skin barrier, locking in moisture for 48 hours to soothe tight and irritated skin.",
    howToUse: "Apply a dime-sized amount to clean skin morning and night.",
  },
  {
    id: "p5",
    slug: "vitamin-c-glow-serum",
    name: "Vitamin C Glow Serum",
    ingredient: "L-Ascorbic Acid 15% + Ferulic Acid",
    price: 699,
    originalPrice: null,
    badge: null,
    badgeType: null,
    image: "/images/Vitamine C.jpg",
    tags: ["Brightening", "Anti-Aging"],
    concerns: ["pigmentation", "anti-aging", "dullness"],
    skinTypes: ["dry", "combination", "normal"],
    rating: "4.8 (1.2k)",
    desc: "An advanced antioxidant formula that visibly brightens the skin, evens tone, and fights signs of photoaging and environmental damage.",
    howToUse: "Apply 2-3 drops to face and neck in the morning. Always follow with SPF.",
  },
  {
    id: "p6",
    slug: "gentle-cream-cleanser",
    name: "Gentle Cream Cleanser",
    ingredient: "Glycerin + Oat Extract",
    price: 399,
    originalPrice: null,
    badge: null,
    badgeType: null,
    image: "/images/Facewash.jpg",
    tags: ["Hydration", "Sensitive"],
    concerns: ["sensitive", "dryness"],
    skinTypes: ["dry", "sensitive", "normal"],
    rating: "4.6 (850)",
    desc: "A soothing, milky cleanser that melts away impurities without disturbing the skin's natural moisture barrier.",
    howToUse: "Massage onto wet or dry skin. Rinse with warm water.",
  },
  {
    id: "p7",
    slug: "pore-refining-toner",
    name: "Pore Refining Toner",
    ingredient: "AHA/BHA Blend + Witch Hazel",
    price: 399,
    originalPrice: null,
    badge: null,
    badgeType: null,
    image: "/images/HA Serum.jpg",
    tags: ["Exfoliation", "Oil Control"],
    concerns: ["acne", "oily", "dullness"],
    skinTypes: ["oily", "combination"],
    rating: "4.7 (1.1k)",
    desc: "A balancing toner that gently exfoliates dead skin cells and clears congestion inside pores, preparing skin for serums.",
    howToUse: "Apply with a cotton pad over entire face and neck after cleansing.",
  },
  {
    id: "p8",
    slug: "hydrating-essence-toner",
    name: "Hydrating Essence Toner",
    ingredient: "Hyaluronic Acid + Centella",
    price: 449,
    originalPrice: null,
    badge: null,
    badgeType: null,
    image: "/images/HA Serumm.jpg",
    tags: ["Hydration", "Soothing"],
    concerns: ["dryness", "sensitive"],
    skinTypes: ["dry", "normal", "sensitive"],
    rating: "4.8 (900)",
    desc: "A dense moisture essence that instantly quenches parched skin, plumping fine lines and calming redness.",
    howToUse: "Pat directly into skin with hands after cleansing.",
  },
  {
    id: "p9",
    slug: "oil-free-gel-moisturizer",
    name: "Oil-Free Gel Moisturizer",
    ingredient: "Squalane + Green Tea",
    price: 549,
    originalPrice: null,
    badge: null,
    badgeType: null,
    image: "/images/Moisturizer new.JPG",
    tags: ["Hydration", "Matte Finish"],
    concerns: ["oily", "acne"],
    skinTypes: ["oily", "combination"],
    rating: "4.7 (1.5k)",
    desc: "A weightless water-gel that delivers essential hydration while absorbing instantly for a shine-free, matte finish all day.",
    howToUse: "Apply morning and night to clean skin.",
  }
];

export const concernsList = [
  { id: "acne", name: "Acne", slug: "acne", icon: "🔴", desc: "Target breakouts and clear congestion" },
  { id: "pigmentation", name: "Dark Spots", slug: "pigmentation", icon: "🌑", desc: "Fade sun spots and hyperpigmentation" },
  { id: "oily", name: "Oil Control", slug: "oily", icon: "💧", desc: "Balance sebum for a matte finish" },
  { id: "sensitive", name: "Sensitive Skin", slug: "sensitive", icon: "🌱", desc: "Soothe redness and protect the barrier" },
  { id: "sun-protection", name: "Sun Protection", slug: "sun-protection", icon: "☀️", desc: "Shield your skin from daily UV rays" },
  { id: "anti-aging", name: "Anti-Aging", slug: "anti-aging", icon: "⏳", desc: "Firm skin and smooth fine lines" },
];

export const heroIngredients = [
  { slug: "niacinamide", name: "Niacinamide", emoji: "💧", sci: "Vitamin B3 – 10%", desc: "Regulates oil production, minimizes pores, and fades dark spots." },
  { slug: "salicylic-acid", name: "Salicylic Acid", emoji: "🫧", sci: "BHA – 2%", desc: "Penetrates deep into pores to dissolve excess oil and dead skin cells." },
  { slug: "vitamin-c", name: "Vitamin C", emoji: "✨", sci: "L-Ascorbic Acid – 15%", desc: "Potent antioxidant that brightens skin tone and boosts collagen." },
  { slug: "hyaluronic-acid", name: "Hyaluronic Acid", emoji: "🌊", sci: "Low + High Molecular Weight", desc: "Holds 1000x its weight in water for deep hydration." },
];

export function getProductBySlug(slug) {
  return products.find(p => p.slug === slug);
}

export function getProductsByConcern(concernSlug) {
  return products.filter(p => p.concerns.includes(concernSlug));
}
